### ISSUE TITLE
java.lang.ClassCastException: com.artifex.mupdfdemo.MuPDFReflowView cannot be cast to com.artifex.mupdfdemo.PageView

### ISSUE THREAD

**Issue by persource** [viavansi/mupdf-android#5]
I tried to implement mupdf library into my app, when i press 'reflow' button it throws an exception. Can you please help to resolved this error.

java.lang.ClassCastException: com.artifex.mupdfdemo.MuPDFReflowView cannot be cast to com.artifex.mupdfdemo.PageView
            at com.artifex.mupdfdemo.ReaderView.onLayout(ReaderView.java:688)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
            at android.view.View.layout(View.java:15671)
            at android.view.ViewGroup.layout(ViewGroup.java:5038)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Thanks.

**Comment by AeonDave** [comment]
same here.
same exception

for now, since i don't need reflow, this is a little fix:

file ReaderView.java
line 686

> if(PageView.class.isInstance(cv)) {
>           currentPage = (PageView) cv;
> ...
> ...
> }

**Comment by kumarbhubnesh** [comment]
Am also getting this exception please the fix.

**Comment by ammaratef45** [comment]
I got the same

**Comment by devdigitalappteam** [comment]
Anyone found the solution for this issue because I am also facing same issue.
